"""Initial migration

Revision ID: 3b2b68b70826
Revises: 
Create Date: 2017-07-12 20:28:11.358881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b2b68b70826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA fnscrapers")
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scraper_name', sa.String(), nullable=False),
    sa.Column('scraper_args', postgresql.JSONB(), nullable=False),
    sa.Column('exclude_nodes', postgresql.JSONB(), nullable=False),
    sa.Column('cron_schedule', sa.String(), nullable=False),
    sa.Column('start_times', postgresql.JSONB(), nullable=False),
    sa.Column('max_runtime_secs', sa.BigInteger(), nullable=False),
    sa.Column('cooldown_time_secs', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.BigInteger(), nullable=True),
    sa.Column('owner_node', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_tag', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('owner_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steal_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_name'),
    schema="fnscrapers",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules', schema="fnscrapers")
    op.execute("DROP SCHEMA fnscrapers")
    # ### end Alembic commands ###
